---
name: Docsite CI
on:
  pull_request:
jobs:
  docsite-build:
    name: docsite test build
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
        with:
          show-progress: false

<<<<<<< HEAD
      - uses: ./.github/actions/setup-python
=======
      - uses: actions/setup-python@v5
>>>>>>> tower/test_stable-2.6
        with:
          python-version: '3.x'

      - name: install tox
        run: pip install tox

      - name: Assure docs can be built
        run: tox -e docs
